# Starter pipeline
  trigger:
  - master

  steps:  
  - task: Kubernetes@1
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: 'Pay-As-You-Go(c111fc5c-4883-4711-ab39-3a82d9fdc483)'
      azureResourceGroup: 'azure-k8stest'
      kubernetesCluster: 'k8stest'
      useClusterAdmin: true
      command: 
      secretType: 'dockerRegistry'
      containerRegistryType: 'Azure Container Registry'
      azureSubscriptionEndpointForSecrets: 'Pay-As-You-Go(c111fc5c-4883-4711-ab39-3a82d9fdc483)'
      azureContainerRegistry: 'containerregistrykuber.azurecr.io'
